name: my first pipeline

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on:
     labels:
      - self-hosted
      - Windows
      - X64


    steps:
      - name: Say Hello
        run: echo "Hello Prakash, pipeline is running successfully"

